apiVersion: apps/v1
kind: Deployment
metadata:
  name:	mqtt-ingestor
  namespace: bluebird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-ingestor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt-ingestor
    spec:
      hostAliases:
        - ip: "10.0.88.76"
          hostnames:
            - "master1.internal"
        - ip: "10.0.87.95"
          hostnames:
            - "master2.internal"
        - ip: "10.0.88.132"
          hostnames:
            - "worker1.internal"
        - ip: "10.0.86.33"
          hostnames:
            - "worker2.internal"
        - ip: "10.0.87.145"
          hostnames:
            - "worker3.internal"
        - ip: "10.0.86.214"
          hostnames:
            - "worker4.internal"
        - ip: "10.0.129.220"
          hostnames:
            - "kafka1.internal"
        - ip: "10.0.88.175"
          hostnames:
            - "database1-vpn"
        - ip: "10.0.88.151"
          hostnames:
            - "database2-vpn"
        - ip: "10.0.87.50"
          hostnames:
            - "database3-vpn"
        - ip: "10.0.88.152"
          hostnames:
            - "druid-1.internal"
      containers:
        - name: mqtt-ingestor
          image: 1l41bgc7.c1.gra9.container-registry.ovh.net/bluebird/mqtt_ingestor:latest
          command: [ "python3", "launcher.py"]
          #command: ["/bin/sh", "-ec", "sleep 1000"]
          env:
            - name: CONF_FILE
              value: "config.json"
          volumeMounts:
          - name: mqtt-ingestor-secret
            mountPath: /app/config.json
            subPath: config.json
      imagePullSecrets:
        - name: odin1pullsecret
      volumes:
        - name: mqtt-ingestor-secret
          secret:
            secretName: mqtt-ingestor-secret
            items:
            - key: config.json
              path: config.json

 #kubectl create secret generic mqtt-ingestor-secret --from-file=config.json=config.json -n bluebird
